VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThongTinKhachHang"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private khacHang As String
Private batDau As String
Private ketThuc As String
Private kmHopDong As Integer
Private soNgayHopDong As Integer
Private donGiaQuaGio As Integer
Private donGiaKmVuot As Integer
Private bienSoXe As String

'-----
'Constructor

